### ISSUE TITLE
Question: How you get the Service token value?

### ISSUE THREAD

**Issue by mictian** [bsdkurt/aws-node-custom-user-pool#1]
Hi, 

First of all, great repo thanks!
I finished this tutorial https://serverless-stack.com/ and I wanted to see how to implement the same but using 100% Infra as Code. For this your solution to create user pools in Cognito is great.

However, there is a piece of the code that I cannot understand yet. In the custom cloudformation resource _CognitoUserPoolUserPool_.
From where you are getting the name of the **CloudFormationCustomUserPoolLambdaFunction** ??

I mean, by default the lambda responsible for the creation of the UserPool will be called _custom-user-pool-dev-cloudFormationCustomUserPool_  not CloudFormationCustomUserPoolLambdaFunction.
I cannot find to what this CloudFormationCustomUserPoolLambdaFunction name is pointing to.

Finally, I know this is more related with CloudFormation rather than your repo, so sorry in advance :laughing:  

Regards,
Mictian

**Comment by bsdkurt** [comment]
Your welcome. Glad someone else is getting some value out of it. 

The CloudFormationCustomUserPoolLambdaFunction name comes from the logical resource name that the serverless framework generates for the lambda. It is comprised of the 'normalized' lambda name: cloudFormationCustomUserPool -> CloudFormationCustomUserPool with LambaFunction appended. See the following link for details:

https://serverless.com/framework/docs/providers/aws/guide/resources/#aws-cloudformation-resource-reference

Best,
-Kurt

**Comment by mictian** [comment]
Thank you very much for your answer.
Cheers! :clinking_glasses:
